### PR TITLE
Utilize Google Fonts v2 API with optimized variable fonts

### PR DESCRIPTION
**Pull request by atiq-cs**
And, provide fallback when var font support is not available

refs,
- https://developers.google.com/fonts/docs/css2

### CODE REVIEW

**Comment by daveaglick** [comment]
Can you also add the fallback described here: https://developers.google.com/fonts/docs/css2#legacy_browser_support to the CSS files - I'm just a little concerned about making the theme exclusive to the most modern browsers. I mean, the support already looks decent, but with a simple fallback I figure it can't hurt to add it. Thoughts?

image

**Comment by atiq-cs** [comment]
Concern is valid. Added fallback. @daveaglick 
I plan to test this more with my blog on some old devices after it gets merged.

**Comment by daveaglick** [comment]
Initial tests looked fine to me, so I'll merge it in and we'll iterate as needed. Thanks (and sorry for the delay)!

**Comment by daveaglick** [comment]
On second thought, I don't love the differences here now that I've viewed it a few times. There's a lack of emphasis on headers so everything kind of runs together.

Before:
image

After:
image

Any idea what's going on here @atiq-cs?

**Comment by daveaglick** [comment]
I'm also noticing the font faces look blander (I.e. the body font is no longer that nice serif). I'm going to revert this back out until we can figure out what's going on here.

**Pull request merged**
