### PR TITLE
Update Vendor Libraries

### PR DESCRIPTION
**Pull request by atiq-cs**
update following,
- bootstrap
- fontawesome-free
- jquery

### CODE REVIEW

**Comment by atiq-cs** [comment]
@daveaglick I followed the same process of original files you had, to update them. I acquired them from `dist` when that was the matched pattern. I got some files from `scss` directory inside when that was the case with original file.

In both cases, I took them from latest release only (no beta or alpha).

Please check individual commits for more info. :)

Please let me know if you have any question. Or, feel free to add anybody who might help with reviewing this.

**Comment by atiq-cs** [comment]
@daveaglick please let me know if you have any questin.

**Comment by daveaglick** [comment]
Thanks for this! It's a big PR though (even if most of it is just replacing/updating files), and front-end libraries have a way of breaking things very subtly (I.e. no compile-time error checking) so it'll probably be a while before I have a chance to double-check all the client updates here and merge them in.

**Comment by atiq-cs** [comment]
Sounds good. Please take your time. 

image

**Comment by daveaglick** [comment]
Now that #23 is merged, I'd be happy to take a look at any additional library updates as well. If we're going to make a bunch of dependency changes, might as well make them all at once. Is there still something in this PR we should apply?

**Comment by atiq-cs** [comment]
This PR is updated by commits in #23 by @rdeago 

 **jquery**: updated by commit# 43ba7cb00
**bootstrap**:  updated by commit# ca33d33b7
**Font Awesome**:  updated by commit# 0dc00e5c9

**Pull request closed without merging**
