### PR TITLE
Update js and css libraries consumed by theme layout file

### PR DESCRIPTION
**Pull request by atiq-cs**
update all js and css reference packages that are outdated

Following are not touched,
- lunr doesn't have an update
- extras.scss

### Test plan
PRs are stacked on top of other. This is the final output.

- verify that original theme tweaks are retained, for example, commit 12fcfe654
ref scss dir, https://github.com/statiqdev/CleanBlog/tree/main/input/scss

Check output as well,

**index page**

image

**post page**

image

### CODE REVIEW

**Comment by atiq-cs** [comment]
Note: Trivial update, please have a look at individual commits inside this PR for further technical details. Cheers!

**Comment by daveaglick** [comment]
Same question here - is there still something here that we should merge on top of #23?

**Comment by atiq-cs** [comment]
For _layout packages update part 1_, ref: 2f5a5ac6f
- prism updated by 5794a6a40
- quicklink by 77f40f060
- pako by 8b78400cf3e3033e75ba1ac3f11fa2389baaab56

note for myself,
- pako etc refs removed in 1eeabd468

**Comment by atiq-cs** [comment]
For *layout packages update part 2: cleanblog js and scss to v6.0.7*, ref: 3ec841c87
has been taken care of by 1eeabd468, thanks @rdeago

**Comment by daveaglick** [comment]
🎉

**Pull request closed without merging**
